Building image in build and added deploy workflow to run on self hosted runner

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,23 +1,24 @@
-name: Build and deploy stack
+name: Build
 
 on:
   workflow_run:
     workflows: ["Test"]
     types: [completed]
-    branches: 
-      - 'development'
+    branches:
+      - "development"
 
 jobs:
-  something:
+  build:
+    name: Build
     runs-on: ubuntu-slim
-    name: Something
+    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           token: ${{ secrets.PAT_TOKEN }}
           fetch-depth: 0
-      
+
       - name: Something step
         run: echo "I've been triggered"
 
@@ -27,66 +28,44 @@ jobs:
           git checkout development
           git branch
           # git fetch origin main
-      
+
       - name: Merge changes
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
-          
+
           git checkout main
           git merge --allow-unrelated-histories --no-ff -m "Merged development" development
           git push origin main
-      
 
-  # build:
-  #   if: github.event.pull_request.merged == true || github.event_name == 'push'
+      - name: Create env file
+        run: |
+          FPATH='.env'
 
-  #   name: Build
-  #   runs-on: self-hosted
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v4
+          cat <<'EOF' > $FNAME
+          ${{ secrets.ENV_FILE }}
+          EOF
 
-  #     - name: Create env file
-  #       run: |
-  #         FPATH='.env'
+          if [ -s $FNAME ]; then
+            echo "$FNAME created successfully"
+            exit 0
+          else
+            echo "Failed to create $FNAME"
+            exit 1
+          fi
 
-  #         cat <<'EOF' > $FNAME
-  #         ${{ secrets.ENV_FILE }}
-  #         EOF
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-  #         if [ -s $FNAME ]; then
-  #           echo "$FNAME created successfully"
-  #           exit 0
-  #         else
-  #           echo "Failed to create $FNAME"
-  #           exit 1
-  #         fi
+      - name: Build backend image
+        run: |
+          docker build --no-cache -t ${{ secrets.DOCKERHUB_IMAGE }}:latest -f docker/Dockerfile .
+          docker push ${{ secrets.DOCKERHUB_IMAGE }}:latest
 
-  #     - name: Login to Docker Hub
-  #       uses: docker/login-action@v3
-  #       with:
-  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
-  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-  #     - name: Initialise swarm
-  #       run: docker swarm init || true
-
-  #     - name: Initialise network
-  #       run: |
-  #         docker network inspect vegate_network || 
-  #           docker network create --attachable --driver overlay vegate_network
-
-  #     - name: Build backend image
-  #       run: |
-  #         docker build --no-cache -t ${{ secrets.DOCKERHUB_IMAGE }}:latest -f docker/Dockerfile .
-  #         docker push ${{ secrets.DOCKERHUB_IMAGE }}:latest
-
-  #     - name: Create docker compose file
-  #       run: |
-  #         cat <<'EOF' > docker/prod-compose.yaml
-  #           ${{ secrets.DOCKER_COMPOSE }}
-  #         EOF
-
-  #     - name: Deploy to stack
-  #       run: docker stack deploy -c docker/prod-compose.yaml vegate_stack
+      - name: Build strategy deploy image
+        run: |
+          docker build --no-cache -t ${{ secrets.STRAT_DEPLOY_DOCKERHUB_IMAGE }}:latest -f docker/strat_deploy.Dockerfile .
+          docker push ${{ secrets.STRAT_DEPLOY_DOCKERHUB_IMAGE }}:latest
