Testing

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,70 +1,74 @@
 name: Build and deploy stack
-on:
-  push:
-    branches: ["main"]
-    
-  pull_request:
-    types: [closed]
-    branches: ["main"]
-
 # on:
-#   workflow_run:
-#     workflows: ["Test"]
-#     types:
-#       - completed
-#     branches:
-#       - main
+#   push:
+#     branches: ["main"]
+    
+#   pull_request:
+#     types: [closed]
+#     branches: ["main"]
+
+on:
+  workflow_run:
+    workflows: ["Test"]
+    branches: 
+      - 'development'
 
 jobs:
-  build:
-    if: github.event.pull_request.merged == true || github.event_name == 'push'
-
-    name: Build
-    runs-on: self-hosted
+  something:
+    runs-on: ubuntu-slim
+    name: Something
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - name: Something step
+        run: echo "I've been triggered"
+  # build:
+  #   if: github.event.pull_request.merged == true || github.event_name == 'push'
 
-      - name: Create env file
-        run: |
-          FPATH='.env'
+  #   name: Build
+  #   runs-on: self-hosted
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-          cat <<'EOF' > $FNAME
-          ${{ secrets.ENV_FILE }}
-          EOF
+  #     - name: Create env file
+  #       run: |
+  #         FPATH='.env'
 
-          if [ -s $FNAME ]; then
-            echo "$FNAME created successfully"
-            exit 0
-          else
-            echo "Failed to create $FNAME"
-            exit 1
-          fi
+  #         cat <<'EOF' > $FNAME
+  #         ${{ secrets.ENV_FILE }}
+  #         EOF
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #         if [ -s $FNAME ]; then
+  #           echo "$FNAME created successfully"
+  #           exit 0
+  #         else
+  #           echo "Failed to create $FNAME"
+  #           exit 1
+  #         fi
 
-      - name: Initialise swarm
-        run: docker swarm init || true
+  #     - name: Login to Docker Hub
+  #       uses: docker/login-action@v3
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Initialise network
-        run: |
-          docker network inspect vegate_network || 
-            docker network create --attachable --driver overlay vegate_network
+  #     - name: Initialise swarm
+  #       run: docker swarm init || true
 
-      - name: Build backend image
-        run: |
-          docker build --no-cache -t ${{ secrets.DOCKERHUB_IMAGE }}:latest -f docker/Dockerfile .
-          docker push ${{ secrets.DOCKERHUB_IMAGE }}:latest
+  #     - name: Initialise network
+  #       run: |
+  #         docker network inspect vegate_network || 
+  #           docker network create --attachable --driver overlay vegate_network
 
-      - name: Create docker compose file
-        run: |
-          cat <<'EOF' > docker/prod-compose.yaml
-            ${{ secrets.DOCKER_COMPOSE }}
-          EOF
+  #     - name: Build backend image
+  #       run: |
+  #         docker build --no-cache -t ${{ secrets.DOCKERHUB_IMAGE }}:latest -f docker/Dockerfile .
+  #         docker push ${{ secrets.DOCKERHUB_IMAGE }}:latest
 
-      - name: Deploy to stack
-        run: docker stack deploy -c docker/prod-compose.yaml vegate_stack
+  #     - name: Create docker compose file
+  #       run: |
+  #         cat <<'EOF' > docker/prod-compose.yaml
+  #           ${{ secrets.DOCKER_COMPOSE }}
+  #         EOF
+
+  #     - name: Deploy to stack
+  #       run: docker stack deploy -c docker/prod-compose.yaml vegate_stack
